### PR TITLE
Added instructions for Kali Linux

### PR DESCRIPTION
**Pull request by alexlauerman**
Not sure if this should go here or not, but I think a good percentage of users will be on Kali, so this should be helpful. I can create an issue if you'd rather have it there. Feel free to reject.

### CODE REVIEW

**Comment by BuffaloWill** [comment]
@alexlauerman thanks for the submission. Let me test a Kali install and I will add this. Cheers!

**Comment by jaypatel3434** [comment]
@BuffaloWill  its also not working in mac i am also getting lots of error

**Comment by BuffaloWill** [comment]
@jaypatel3434 could you create an issue with what you are seeing? 

I've updated the README to reflect @alexlauerman recommendations. Thanks! Sorry for the wicked slow turn around.

**Comment by jaypatel3434** [comment]
yes sure brother like when install each and every thing after that it give me some error it can’t run in mac don’t know brother 
if you don’t mind then plz can come on team viewer and can fix the problem

**Pull request closed without merging**
